### ISSUE TITLE
Question about mybatis

### ISSUE THREAD

**Issue by kopax** [inmaytide/orbit#1]
Hello @inmaytide , following https://github.com/hatunet/spring-data-mybatis/issues/144,  I permit my self to ask you help.

I can see that you are playing with spring-data-mybatis in your project and maybe you can give me a little to understand it.

I need to have my custom `SELECT_CONDITION_INNER` when the xml rendering happen:

https://github.com/hatunet/spring-data-mybatis/blob/adeae420c8f09a88c0c7aed5676ccc1401954c33/src/main/java/org/springframework/data/mybatis/repository/support/MybatisSimpleRepositoryMapperGenerator.java#L125

I have tried to add it in my mapper, but then it complain it already exist because of the default one.

Do you know how I can preload mapper in the configuration before the render happen ?

Thanks in advance,

**Comment by inmaytide** [comment]
https://github.com/hatunet/spring-data-mybatis/issues/138
Use beforeMapperLocations  to config your mappers location

**Comment by kopax** [comment]
@inmaytide this is exactly what I am looking for. I was looking in the source of `spring-data-mybatis` and not `spring-boot-starter-data-mybatis`.

I am using also using `spring-boot-starter-data-mybatis` but adding a breakpoint here https://github.com/hatunet/spring-boot-starter-data-mybatis/blob/master/src/main/java/org/springframework/data/mybatis/autoconfiguration/MybatisRepositoriesAutoConfiguration.java#L69 but it never get through.

Do you the steps to configure beforeMapperLocations ?

**Comment by kopax** [comment]
I managed by removing `@EnableMybatisRepositories` annotation.

**Comment by kopax** [comment]
Thanks a lot for your answer, it really helped me, there is one last step be able to start again my Tomcat.

I was creating before my own `sqlSessionFactory` where I included my typeAliases.

```java
    @Bean
    public SqlSessionFactoryBean sqlSessionFactory() throws Exception {
        final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource());
        sessionFactory.setTypeHandlers(new TypeHandler[] {
                new InstantTypeHandler(),
                new LocalDateTimeTypeHandler(),
                new LocalDateTypeHandler(),
                new LocalTimeTypeHandler(),
                new OffsetDateTimeTypeHandler(),
                new OffsetTimeTypeHandler(),
                new ZonedDateTimeTypeHandler(),
                new YearTypeHandler(),
                new MonthTypeHandler(),
                new CommaSeparatedTypeHandler(),
                new JsonMapTypeHandler(),
        });
        sessionFactory.setTypeAliases(new Class[] {
                Role.class,
                User.class,
                OAuthClient.class,
        });
        return sessionFactory;
    }

```

`MybatisRepositoryConfigExtension` does this configuration.

I have checked the `MybatisProperties` and it is possible to load my TypeHandlers but it does not take care of typeAliases.

Do you know how I can configure typeAliases when using `spring-boot-starter-data-mybatis` ?

I have tried adding `@TypeAlias("Role")` but I still have `BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'Role'.`

**Comment by kopax** [comment]
Solved it with
